apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      restartPolicy: Always
      containers:
      - name: grafana
        image: grafana:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ./livenessProbe.sh
          initialDelaySeconds: 15
          periodSeconds: 3
