apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:local
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        env:
        - name: WP_IP
          value: "WORDPRESS_IP"
        - name: PMA_IP
          value: "PHPMYADMIN_IP"
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 30
        #   periodSeconds: 3
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ./livenessProbe.sh
          initialDelaySeconds: 15
          periodSeconds: 3
        imagePullPolicy: Never
