#!/bin/sh

sed -i.bak 's/INFLUX_IP/'"$INFLUXDB_SERVICE_PORT_8086_TCP_ADDR"'/' /etc/telegraf/telegraf.conf

nohup sh /root/nohup-mysql.sh > /root/logs 2>&1 &
/usr/bin/mysql_install_db --user=mysql --datadir="/var/lib/mysql" && echo "START MYSQL" > /log.txt
/usr/bin/mysqld_safe --datadir="/var/lib/mysql" --log-error="/etc/mysql.log" > /etc/mysql_console.log & echo "MYSQL STARTED" >> /log.txt && /usr/bin/telegraf
