apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
      - name: wordpress
        image: wordpress:local
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: http
        env:
          - name: DB_NAME
            value: db_wordpress
          - name: DB_USER
            value: wp_admin
          - name: DB_PASSWORD
            value: admin
          - name: MYSQL_IP
            value: "MS_IP"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ./livenessProbe.sh
          initialDelaySeconds: 15
          periodSeconds: 3
        # livenessProbe:
        #   tcpSocket:
        #     port: 5050
        #   initialDelaySeconds: 30
        #   periodSeconds: 3
