#!/bin/bash

sed -i.bak 's/INFLUX_IP/'"$INFLUXDB_SERVICE_PORT_8086_TCP_ADDR"'/' /etc/telegraf/telegraf.conf
sed -i.bak 's/MYSQL_IP/'$MYSQL_SERVICE_PORT_3306_TCP_ADDR'/' /www/phpmyadmin/config.inc.php

echo "Running server at /www/phpmyadmin/:"
rc-service nginx start
rc-service php-fpm7 start
/usr/bin/telegraf
